enableTransparentWorkspaces: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "@yarnpkg/plugin-constraints"

unsafeHttpWhitelist:
  - localhost

# This path should always match the one in .yarnrc
yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
